### ISSUE TITLE
Please add KDD 2019 paper, code, data

### ISSUE THREAD

**Issue by srijankr** [naganandy/graph-based-deep-learning-literature#13]
Hi!

Thank you for this awesome repository!

Could you please add the following paper, code, and data link to the repository:
Paper: Predicting Dynamic Embedding Trajectory in Temporal Interaction Networks
Authors: Srijan Kumar, Xikun Zhang, Jure Leskovec
Venue: ACM SIGKDD 2019 (Proceedings of the 25th ACM SIGKDD international conference on Knowledge discovery and data mining)
Project page: http://snap.stanford.edu/jodie/
Code: https://github.com/srijankr/jodie/
All datasets: http://snap.stanford.edu/jodie/
Spotlight: https://www.youtube.com/watch?v=ItBmU8681j0

Many thanks,
Srijan

**Comment by naganandy** [comment]
Thanks for sharing the work! Just added it to the repository!
