### ISSUE TITLE
EP: NeurIPS paper from 2017

### ISSUE THREAD

**Issue by nle-ml** [naganandy/graph-based-deep-learning-literature#22]
Hi and thanks a lot for the cool repo. Very comprehensive. Wanted to advertise our NeurIPS paper from 2017. It’s an unsupervised GNN (the first as far as I can tell for node classification). Unfortunately similar to GraphSage which came out in the same conference :-).   Here it is:

https://papers.nips.cc/paper/7097-learning-graph-representations-with-embedding-propagation.pdf

**Comment by naganandy** [comment]
Hi and thanks a lot for sharing the NeurIPS paper! Just added it to the repo!
