### ISSUE TITLE
Relevant graph machine learning papers at NeurIPS 2020

### ISSUE THREAD

**Issue by hyren** [naganandy/graph-based-deep-learning-literature#26]
Great post and collection of papers! 

Just want to add a NeurIPS 20 paper to the repo [Beta Embeddings for Multi-Hop Logical Reasoning in Knowledge Graphs](https://arxiv.org/abs/2010.11465). We design new set representations with neural logical operations on large heterogeneous KGs. It's the first work that implements all neural first-order logical operations (including negation) over sets. Please feel free to add it to Learning with Sets or Knowledge Graphs.

Besides, our NeurIPS 20 work [Graph Information Bottleneck](https://arxiv.org/abs/2010.12811) learns an optimal node/graph representation by optimizing variational bounds on mutual information. It demonstrates strong robustness against adversarial attacks. Please feel free to categorize it to adversarial attack/robustness. 

Both work are open sourced at [BetaE](http://snap.stanford.edu/betae/) and [GIB](http://snap.stanford.edu/gib/).

Thanks for your efforts, and really nice work!

**Comment by naganandy** [comment]
Thanks a lot for the info! I've just added BetaE to learning with sets and GIB to robustness!

**Comment by hyren** [comment]
Thanks!
