### ISSUE TITLE
Some related papers

### ISSUE THREAD

**Issue by marlin-codes** [naganandy/graph-based-deep-learning-literature#32]
Thanks for the awsome project. The followings are some related papers. Thanks
-------------------------------------------------------------------------------------------------------

1. Survey
Title: Hyperbolic Graph Neural Networks: A Review of Methods and Applications 
Arxiv: https://arxiv.org/abs/2202.13852 
Github pages https://github.com/marlin-codes/HGNNs

2. Hyperbolic GNN for temporal network embedding, 
KDD 2021, 
Title: Discrete-time Temporal Network Embedding via Implicit Hierarchical Learning in Hyperbolic Space
Arxiv: https://arxiv.org/abs/2107.03767 
ACM: https://dl.acm.org/doi/abs/10.1145/3447548.3467422
Code: https://github.com/marlin-codes/HTGN

3. Overcome oversmoothing problem in dynamic graph, 
ICDM 2020
Title: FeatureNorm: L2 Feature Normalization for Dynamic Graph Embedding
https://arxiv.org/abs/2103.00164
Code: https://github.com/marlin-codes/FeatureNorm-ICDM2020

**Comment by naganandy** [comment]
Thanks, added them!

**Comment by marlin-codes** [comment]
Thanks for the awsome project. The followings are some new related papers. Thanks

update, July 19 2022

Topic: Graph Collaborative Filtering
HRCF: Enhancing Collaborative Filtering via Hyperbolic Geometric Regularization
Proceedings of the ACM Web Conference 2022 (WWW '22);
https://arxiv.org/abs/2204.08176
https://github.com/marlin-codes/HRCF

Topic: Graph Collaborative Filtering
HICF: Hyperbolic Informative Collaborative Filtering
Proceedings of the 28th ACM SIGKDD Conference on Knowledge Discovery and Data Mining
(KDD ’22)
https://arxiv.org/abs/2207.09051
