### ISSUE TITLE
This is not an issue, just a discussion thread.

### ISSUE THREAD

**Issue by benedekrozemberczki** [naganandy/graph-based-deep-learning-literature#7]
So these are just ideas for discussion:

1. Do You want to include papers from the Graph Representation Learning workshops in higher tier conferences (KDD, AAAI, NIPS)?
2. There are fairly good papers in conferences such as ASONAM or WSDM.

**Comment by benedekrozemberczki** [comment]
Can we also add this one:

https://github.com/benedekrozemberczki/GAM

It is a KDD 18 paper.

**Comment by naganandy** [comment]
Thanks for the ideas and the KDD paper (just added it)!  

We could surely have one link for each graph representation learning workshop. All papers in these workshops are relevant and a few top papers from these workshops (e.g. DGI, LanczosNet in NIPS workshop) get published in top conferences (e.g. ICLR 2019) anyway!
